apiVersion: v1
kind: Service
metadata:
  labels:
    app: geth
  name: geth
  namespace: default
spec:
  selector:
    app: geth
  ports:
  - name: rpc
    protocol: TCP
    port: 8545
    targetPort: 8545
